# Generated for the Prompt 04 financial module baseline.

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("compras", "0001_initial"),
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("tipo", models.CharField(choices=[("receita", "Receita"), ("despesa", "Despesa")], db_index=True, max_length=20)),
                ("descricao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="categoriafinanceira_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="categoriafinanceira_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["tipo", "nome"]},
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="centrocusto_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="centrocusto_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["codigo"]},
        ),
        migrations.CreateModel(
            name="Parcelamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=180)),
                ("quantidade_parcelas", models.PositiveIntegerField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("data_primeiro_vencimento", models.DateField()),
                ("intervalo_meses", models.PositiveIntegerField(default=1)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="parcelamento_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="parcelamento_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("numero_lancamento", models.CharField(db_index=True, max_length=30, unique=True)),
                ("descricao", models.CharField(max_length=220)),
                ("valor_original", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("valor_atual", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField(db_index=True)),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("parcialmente_pago", "Parcialmente pago"), ("pago", "Pago"), ("vencido", "Vencido"), ("cancelado", "Cancelado")], db_index=True, default="pendente", max_length=30)),
                ("tipo_pagamento", models.CharField(blank=True, max_length=80)),
                ("observacao", models.TextField(blank=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar", to="financeiro.categoriafinanceira")),
                ("centro_custo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar", to="financeiro.centrocusto")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contapagar_created", to=settings.AUTH_USER_MODEL)),
                ("fornecedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar", to="fornecedores.fornecedor")),
                ("parcelamento", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar", to="financeiro.parcelamento")),
                ("pedido_compra_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar", to="compras.pedidocompra")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contapagar_updated", to=settings.AUTH_USER_MODEL)),
                ("usuario_responsavel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_pagar_responsavel", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["data_vencimento", "numero_lancamento"]},
        ),
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("numero_lancamento", models.CharField(db_index=True, max_length=30, unique=True)),
                ("descricao", models.CharField(max_length=220)),
                ("valor_original", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("valor_atual", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField(db_index=True)),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("parcialmente_recebido", "Parcialmente recebido"), ("recebido", "Recebido"), ("vencido", "Vencido"), ("cancelado", "Cancelado")], db_index=True, default="pendente", max_length=30)),
                ("forma_recebimento", models.CharField(blank=True, max_length=80)),
                ("observacao", models.TextField(blank=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_receber", to="financeiro.categoriafinanceira")),
                ("centro_custo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_receber", to="financeiro.centrocusto")),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_receber", to="clientes.cliente")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contareceber_created", to=settings.AUTH_USER_MODEL)),
                ("parcelamento", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contas_receber", to="financeiro.parcelamento")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contareceber_updated", to=settings.AUTH_USER_MODEL)),
                ("usuario_responsavel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contas_receber_responsavel", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["data_vencimento", "numero_lancamento"]},
        ),
        migrations.CreateModel(
            name="BaixaFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(choices=[("pagamento", "Pagamento"), ("recebimento", "Recebimento")], db_index=True, max_length=20)),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("data_pagamento", models.DateField(db_index=True)),
                ("multa", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("juros", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("desconto", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("observacao", models.TextField(blank=True)),
                ("conta_pagar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="baixas", to="financeiro.contapagar")),
                ("conta_receber", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="baixas", to="financeiro.contareceber")),
                ("usuario_responsavel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="baixas_financeiras", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-data_pagamento", "-id"]},
        ),
        migrations.AddConstraint(model_name="categoriafinanceira", constraint=models.UniqueConstraint(fields=("nome", "tipo"), name="financeiro_categoria_nome_tipo_uniq")),
        migrations.AddIndex(model_name="categoriafinanceira", index=models.Index(fields=["tipo", "is_active"], name="financeiro__tipo_1ee0e2_idx")),
        migrations.AddIndex(model_name="centrocusto", index=models.Index(fields=["codigo", "is_active"], name="financeiro__codigo_dacb56_idx")),
        migrations.AddConstraint(model_name="contapagar", constraint=models.CheckConstraint(check=models.Q(valor_original__gt=0), name="financeiro_cp_valor_original_gt_0")),
        migrations.AddConstraint(model_name="contapagar", constraint=models.CheckConstraint(check=models.Q(valor_atual__gte=0), name="financeiro_cp_valor_atual_gte_0")),
        migrations.AddIndex(model_name="contapagar", index=models.Index(fields=["status", "data_vencimento"], name="financeiro__status_190cc7_idx")),
        migrations.AddIndex(model_name="contapagar", index=models.Index(fields=["fornecedor", "status"], name="financeiro__fornece_ecb486_idx")),
        migrations.AddIndex(model_name="contapagar", index=models.Index(fields=["centro_custo", "status"], name="financeiro__centro__356f55_idx")),
        migrations.AddConstraint(model_name="contareceber", constraint=models.CheckConstraint(check=models.Q(valor_original__gt=0), name="financeiro_cr_valor_original_gt_0")),
        migrations.AddConstraint(model_name="contareceber", constraint=models.CheckConstraint(check=models.Q(valor_atual__gte=0), name="financeiro_cr_valor_atual_gte_0")),
        migrations.AddIndex(model_name="contareceber", index=models.Index(fields=["status", "data_vencimento"], name="financeiro__status_234117_idx")),
        migrations.AddIndex(model_name="contareceber", index=models.Index(fields=["cliente", "status"], name="financeiro__cliente_ae85ef_idx")),
        migrations.AddIndex(model_name="contareceber", index=models.Index(fields=["centro_custo", "status"], name="financeiro__centro__d3f212_idx")),
        migrations.AddConstraint(model_name="baixafinanceira", constraint=models.CheckConstraint(check=models.Q(valor_pago__gt=0), name="financeiro_baixa_valor_gt_0")),
        migrations.AddConstraint(model_name="baixafinanceira", constraint=models.CheckConstraint(check=models.Q(multa__gte=0), name="financeiro_baixa_multa_gte_0")),
        migrations.AddConstraint(model_name="baixafinanceira", constraint=models.CheckConstraint(check=models.Q(juros__gte=0), name="financeiro_baixa_juros_gte_0")),
        migrations.AddConstraint(model_name="baixafinanceira", constraint=models.CheckConstraint(check=models.Q(desconto__gte=0), name="financeiro_baixa_desconto_gte_0")),
        migrations.AddIndex(model_name="baixafinanceira", index=models.Index(fields=["tipo", "data_pagamento"], name="financeiro__tipo_82b3f3_idx")),
        migrations.AddIndex(model_name="baixafinanceira", index=models.Index(fields=["conta_pagar"], name="financeiro__conta_p_c77cf9_idx")),
        migrations.AddIndex(model_name="baixafinanceira", index=models.Index(fields=["conta_receber"], name="financeiro__conta_r_e1a72f_idx")),
    ]
