# Generated for the Prompt 05 fiscal module baseline.

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("estoque", "0001_initial"),
        ("financeiro", "0001_initial"),
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("razao_social", models.CharField(max_length=180)),
                ("nome_fantasia", models.CharField(blank=True, max_length=180)),
                ("cnpj", models.CharField(db_index=True, max_length=14, unique=True)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                ("inscricao_municipal", models.CharField(blank=True, max_length=30)),
                ("regime_tributario", models.CharField(choices=[("simples_nacional", "Simples Nacional"), ("lucro_presumido", "Lucro Presumido"), ("lucro_real", "Lucro Real")], max_length=30)),
                ("cnae", models.CharField(blank=True, max_length=20)),
                ("endereco_fiscal", models.TextField()),
                ("municipio_ibge", models.CharField(max_length=7)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=8)),
                ("certificado_a1", models.FileField(blank=True, upload_to="certificados/")),
                ("certificado_senha_protegida", models.TextField(blank=True)),
                ("ambiente", models.CharField(choices=[("homologacao", "Homologacao"), ("producao", "Producao")], default="homologacao", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="empresafiscal_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="empresafiscal_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["razao_social"]},
        ),
        migrations.CreateModel(
            name="ClienteFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cpf_cnpj", models.CharField(db_index=True, max_length=14)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                ("indicador_ie", models.CharField(default="nao_contribuinte", max_length=30)),
                ("endereco_fiscal", models.TextField()),
                ("municipio_ibge", models.CharField(max_length=7)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=8)),
                ("email_fiscal", models.EmailField(blank=True, max_length=254)),
                ("cliente", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dados_fiscais", to="clientes.cliente")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clientefiscal_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clientefiscal_updated", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="FornecedorFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cpf_cnpj", models.CharField(db_index=True, max_length=14)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                ("indicador_ie", models.CharField(default="nao_contribuinte", max_length=30)),
                ("endereco_fiscal", models.TextField()),
                ("municipio_ibge", models.CharField(max_length=7)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=8)),
                ("email_fiscal", models.EmailField(blank=True, max_length=254)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fornecedorfiscal_created", to=settings.AUTH_USER_MODEL)),
                ("fornecedor", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dados_fiscais", to="fornecedores.fornecedor")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fornecedorfiscal_updated", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="NaturezaOperacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("codigo", models.CharField(db_index=True, max_length=20, unique=True)),
                ("descricao", models.CharField(max_length=180)),
                ("tipo_operacao", models.CharField(choices=[("venda", "Venda"), ("compra", "Compra"), ("devolucao", "Devolucao"), ("remessa", "Remessa"), ("retorno", "Retorno"), ("bonificacao", "Bonificacao"), ("ajuste", "Ajuste")], db_index=True, max_length=20)),
                ("cfop_padrao", models.CharField(max_length=4)),
                ("movimenta_estoque", models.BooleanField(default=True)),
                ("gera_financeiro", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="naturezaoperacao_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="naturezaoperacao_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["codigo"]},
        ),
        migrations.CreateModel(
            name="ProdutoFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ncm", models.CharField(db_index=True, max_length=8)),
                ("cest", models.CharField(blank=True, max_length=7)),
                ("cfop_padrao", models.CharField(max_length=4)),
                ("unidade_comercial", models.CharField(max_length=10)),
                ("unidade_tributavel", models.CharField(max_length=10)),
                ("origem_mercadoria", models.CharField(default="0", max_length=1)),
                ("cst_csosn", models.CharField(max_length=4)),
                ("aliquota_icms", models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=7, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("aliquota_pis", models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=7, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("aliquota_cofins", models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=7, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("aliquota_ipi", models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=7, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="produtofiscal_created", to=settings.AUTH_USER_MODEL)),
                ("produto", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dados_fiscais", to="estoque.produto")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="produtofiscal_updated", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("numero", models.PositiveIntegerField()),
                ("serie", models.PositiveIntegerField(default=1)),
                ("chave_acesso", models.CharField(blank=True, db_index=True, max_length=44)),
                ("protocolo", models.CharField(blank=True, max_length=60)),
                ("ambiente", models.CharField(choices=[("homologacao", "Homologacao"), ("producao", "Producao")], default="homologacao", max_length=20)),
                ("tipo_emissao", models.CharField(default="normal", max_length=30)),
                ("tipo_operacao", models.CharField(choices=[("venda", "Venda"), ("compra", "Compra"), ("devolucao", "Devolucao"), ("remessa", "Remessa"), ("retorno", "Retorno"), ("bonificacao", "Bonificacao"), ("ajuste", "Ajuste")], max_length=20)),
                ("data_emissao", models.DateTimeField(auto_now_add=True)),
                ("data_saida_entrada", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("validada", "Validada"), ("assinada", "Assinada"), ("enviada", "Enviada"), ("autorizada", "Autorizada"), ("rejeitada", "Rejeitada"), ("cancelada", "Cancelada"), ("denegada", "Denegada")], db_index=True, default="rascunho", max_length=20)),
                ("valor_produtos", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("valor_frete", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("valor_desconto", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("valor_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("xml_autorizado", models.TextField(blank=True)),
                ("xml_cancelamento", models.TextField(blank=True)),
                ("danfe_pdf", models.FileField(blank=True, upload_to="danfes/")),
                ("motivo_rejeicao", models.TextField(blank=True)),
                ("categoria_financeira", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="financeiro.categoriafinanceira")),
                ("centro_custo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="financeiro.centrocusto")),
                ("conta_pagar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="financeiro.contapagar")),
                ("conta_receber", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="financeiro.contareceber")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notafiscal_created", to=settings.AUTH_USER_MODEL)),
                ("destinatario_cliente", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="clientes.cliente")),
                ("destinatario_fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="fornecedores.fornecedor")),
                ("emitente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notas_emitidas", to="fiscal.empresafiscal")),
                ("natureza_operacao", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to="fiscal.naturezaoperacao")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notafiscal_updated", to=settings.AUTH_USER_MODEL)),
                ("usuario_responsavel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notas_fiscais", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-data_emissao", "-id"]},
        ),
        migrations.CreateModel(
            name="ItemNotaFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=220)),
                ("cfop", models.CharField(max_length=4)),
                ("ncm", models.CharField(max_length=8)),
                ("cst_csosn", models.CharField(max_length=4)),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.0001"))])),
                ("valor_unitario", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("valor_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("desconto", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0"))])),
                ("base_icms", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("valor_icms", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("base_pis", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("valor_pis", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("base_cofins", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("valor_cofins", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("base_ipi", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("valor_ipi", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("nota_fiscal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="fiscal.notafiscal")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="itens_nfe", to="estoque.produto")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="EventoFiscal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tipo_evento", models.CharField(choices=[("validacao", "Validacao"), ("assinatura", "Assinatura"), ("envio", "Envio"), ("autorizacao", "Autorizacao"), ("rejeicao", "Rejeicao"), ("cancelamento", "Cancelamento"), ("erro_comunicacao", "Erro de Comunicacao"), ("retorno_sefaz", "Retorno SEFAZ")], db_index=True, max_length=30)),
                ("codigo_retorno", models.CharField(blank=True, max_length=20)),
                ("mensagem", models.TextField()),
                ("protocolo", models.CharField(blank=True, max_length=60)),
                ("xml_retorno", models.TextField(blank=True)),
                ("data_evento", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("nota_fiscal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="eventos", to="fiscal.notafiscal")),
                ("usuario_responsavel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-data_evento", "-id"]},
        ),
        migrations.AddConstraint(model_name="notafiscal", constraint=models.UniqueConstraint(fields=("numero", "serie", "emitente", "ambiente"), name="fiscal_nfe_numero_serie_emitente_ambiente_uniq")),
        migrations.AddConstraint(model_name="notafiscal", constraint=models.CheckConstraint(check=models.Q(valor_frete__gte=0), name="fiscal_nfe_frete_gte_0")),
        migrations.AddConstraint(model_name="notafiscal", constraint=models.CheckConstraint(check=models.Q(valor_desconto__gte=0), name="fiscal_nfe_desconto_gte_0")),
        migrations.AddIndex(model_name="notafiscal", index=models.Index(fields=["status", "data_emissao"], name="fiscal_not_status_15e2df_idx")),
        migrations.AddIndex(model_name="notafiscal", index=models.Index(fields=["chave_acesso"], name="fiscal_not_chave__63e37c_idx")),
        migrations.AddConstraint(model_name="itemnotafiscal", constraint=models.CheckConstraint(check=models.Q(quantidade__gt=0), name="fiscal_item_quantidade_gt_0")),
        migrations.AddConstraint(model_name="itemnotafiscal", constraint=models.CheckConstraint(check=models.Q(valor_unitario__gte=0), name="fiscal_item_valor_unit_gte_0")),
        migrations.AddIndex(model_name="eventofiscal", index=models.Index(fields=["nota_fiscal", "tipo_evento"], name="fiscal_eve_nota_fi_6a8a8b_idx")),
    ]
