DEFAULT_ROLES = [
    ("administrador", "Administrador"),
    ("diretoria", "Diretoria"),
    ("financeiro", "Financeiro"),
    ("compras", "Compras"),
    ("estoque", "Estoque"),
    ("fiscal", "Fiscal"),
    ("comercial", "Comercial"),
    ("operacional", "Operacional"),
    ("supervisor", "Supervisor"),
]


DEFAULT_PERMISSIONS = [
    "estoque.produto.visualizar",
    "estoque.produto.criar",
    "estoque.produto.editar",
    "estoque.produto.excluir",
    "compras.pedido.visualizar",
    "compras.pedido.aprovar",
    "financeiro.conta_pagar.visualizar",
    "financeiro.conta_pagar.baixar",
    "financeiro.conta_receber.visualizar",
    "financeiro.conta_receber.baixar",
    "fiscal.nfe.visualizar",
    "fiscal.nfe.emitir",
    "os.ordem.visualizar",
    "os.ordem.finalizar",
    "orcamentos.orcamento.visualizar",
    "orcamentos.orcamento.aprovar",
    "clientes.cliente.visualizar",
    "clientes.cliente.editar",
    "fornecedores.fornecedor.visualizar",
    "fornecedores.fornecedor.editar",
    "relatorios.dashboard.visualizar",
    "relatorios.exportacao.gerar",
    "accounts.usuario.visualizar",
    "accounts.usuario.gerenciar",
    "accounts.perfil.gerenciar",
]
